//
//  DetailsRouter.swift
//  Random picture
//
//  Created by craig on 08/07/2020.
//  Copyright (c) 2020 Craig Josse. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailsRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol DetailsDataPassing {
  var dataStore: DetailsDataStore? { get }
}

class DetailsRouter: NSObject, DetailsRoutingLogic, DetailsDataPassing {
  weak var viewController: DetailsViewController?
  var dataStore: DetailsDataStore?
}
