//
//  DetailsInteractor.swift
//  Random picture
//
//  Created by craig on 08/07/2020.
//  Copyright (c) 2020 Craig Josse. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailsBusinessLogic {
  func doSomething()
}

protocol DetailsDataStore {
  var message: String? { get set }
}

class DetailsInteractor: DetailsBusinessLogic, DetailsDataStore {
    var message: String?
  var presenter: DetailsPresentationLogic?
  var worker: DetailsWorker?
  func doSomething() {
    worker = DetailsWorker()
    let detailDataMessage = Details.DetailsText(message:
    """
    You can find these photos
    on the unsplash website.\nAuthor :
    """)
    presenter?.presentSomething(data: detailDataMessage)
  }
}
