//
//  DetailsModels.swift
//  Random picture
//
//  Created by craig on 08/07/2020.
//  Copyright (c) 2020 Craig Josse. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Details {
    struct DetailsText {
        var message: String
    }
    struct ViewModel {
        var message: String
    }
}
